using Wevito.VNext.Core.Audit;

namespace Wevito.VNext.Core;

public sealed class PlainLanguageExplainer
{
    private readonly Action<string>? _warnUnknownPacketKind;

    public PlainLanguageExplainer(Action<string>? warnUnknownPacketKind = null)
    {
        _warnUnknownPacketKind = warnUnknownPacketKind;
    }

    public static IReadOnlyList<string> KnownPacketKinds { get; } =
    [
        "activity_summary",
        "audit_ledger_cleanup_dry_run",
        "audit_ledger_cleanup_rolled_back",
        "audit_ledger_cleanup_summary",
        "ai_identity_set",
        "agent_slot_assigned",
        "agent_slot_renamed",
        "agent_slot_status_changed",
        "assetInventory",
        "audioAssist",
        "autonomous_scope_enabled_changed",
        "autonomous_scope_preview",
        "autonomous_scope_tick",
        "benchmark_baseline_updated",
        "benchmark_case_approved",
        "benchmark_case_bookmarked_from_chat",
        "benchmark_case_drafted",
        "benchmark_case_rejected",
        "benchmark_case_revised",
        "benchmark_regression_detected",
        "benchmark_run",
        "buildProof",
        "chat_search_performed",
        "chat_session_archived",
        "chat_session_started",
        "chat_session_title_set",
        "chat_turn_cancelled",
        "chat_turn_completed",
        "codePatchPlan",
        "codeReview",
        "codex_loop_heartbeat",
        "codex_loop_paused",
        "codex_loop_resumed",
        "codex_compile_throttled",
        "codex_phase_blocked",
        "codex_phase_completed",
        "codex_phase_retried",
        "codex_phase_started",
        "coexistence_trigger_cleared",
        "coexistence_trigger_fired",
        "context_budget_pressure",
        "dnd_state_changed",
        "disk_io_budget_throttled",
        "evidence_dashboard_summary_exported",
        "audio_played",
        "focus_protected",
        "game_mode_cleared",
        "game_mode_detected",
        "guardedMutation",
        "kill_switch",
        "learning_promotion",
        "localDocs",
        "local_document_index_built",
        "local_document_index_refused",
        "local_document_query_completed",
        "local_brain_heartbeat",
        "local_brain_onboarding_panel_shown",
        "local_brain_setup_instruction_copied",
        "local_brain_smoke_test_completed",
        "local_brain_status_panel_shown",
        "local_file_preview",
        "local_model_call",
        "model_bootstrap_required",
        "model_bootstrap_runtime_absent",
        "mutation_apply",
        "mutation_proposal",
        "mutation_rollback",
        "multi_monitor_preference_set",
        "notification_deferred",
        "notification_delivered",
        "petState",
        "pet_animation_forced",
        "pet_cursor_curiosity_fired",
        "pet_goal_changed",
        "pet_interaction_logged",
        "pet_micro_behavior",
        "pet_particle_effect_played",
        "pet_state_tool_invoked",
        "pet_fps_snapshot",
        "pet_fps_violation",
        "pet_cursor_reactivity_fired",
        "pinned_message_added",
        "pinned_message_removed",
        "proof_packet",
        "process_crash_recovery",
        "process_priority_boosted",
        "process_priority_set",
        "promotion_criteria_snapshot",
        "promotion_decision",
        "ram_pressure_emergency",
        "ram_pressure_event",
        "budget_meter_snapshot",
        "focus_steal_snapshot",
        "first_launch_completed",
        "first_launch_step_completed",
        "first_run_choice_recorded",
        "image_gen_idle_guard_blocked",
        "power_resume",
        "power_sleep",
        "runtime_session",
        "runtime_session_end",
        "runtime_session_heartbeat",
        "runtime_session_paused",
        "runtime_autonomous_beta_user_consent",
        "runtime_session_start",
        "retrieval_triggered",
        "scheduler_proposal",
        "screenCapture",
        "session_lock",
        "session_unlock",
        SelfImprovementPacketKinds.ProposalDrafted,
        SelfImprovementPacketKinds.ConstitutionalReviewed,
        SelfImprovementPacketKinds.DryRunCompleted,
        SelfImprovementPacketKinds.EvalCompleted,
        SelfImprovementPacketKinds.ApplyAwaitingApproval,
        SelfImprovementPacketKinds.ApplyRefused,
        SelfImprovementPacketKinds.ApplyCompleted,
        SelfImprovementPacketKinds.RollbackVerified,
        SelfImprovementPacketKinds.MaturityClockReset,
        SelfImprovementPacketKinds.JudgeCritique,
        SelfImprovementPacketKinds.ApplyPrerequisiteCheck,
        SelfImprovementPacketKinds.LocalRuntimeProbe,
        SelfImprovementPacketKinds.ScoringDryRun,
        SelfImprovementPacketKinds.ApplyRunnerStatusReport,
        "soak_window_end",
        "spriteAudit",
        "sprite_cleanup_help_card_drafted",
        "sprite_repair_queue_built",
        "sprite_repair_batch",
        "sprite_repair_batch_rolled_back",
        "sprite_repair_triage_card_enriched",
        "sprite_repair_triage_card_drafted",
        "summarization_run",
        "train_plan",
        "translateText",
        "tuning_apply",
        "tuning_rollback",
        "tool_invocation_started",
        "tool_invocation_completed",
        "tool_hub_layout_changed",
        "tool_result_truncated",
        "tool_registry_loaded",
        "tool_registry_setting",
        "tier_priority_adjusted",
        "user_interacting_state_cleared",
        "user_interacting_state_entered",
        "user_protection_floor_blocked_reservation",
        "web_fetch"
    ];

    public string Explain(AuditLedgerRow row)
    {
        var label = ExplainPacketKind(row.PacketKind);
        var badges = new List<string>();
        if (row.DidUseNetwork)
        {
            badges.Add("used network");
        }

        if (row.DidUseHostedAi)
        {
            badges.Add("used hosted AI");
        }

        if (row.DidMutate)
        {
            badges.Add("changed files");
        }

        return badges.Count == 0 ? label : $"{label} ({string.Join(", ", badges)})";
    }

    public string ExplainPacketKind(string packetKind)
    {
        return packetKind switch
        {
            "activity_summary" => "Summarized Wevito's recent helper activity.",
            "audit_ledger_cleanup_dry_run" => "Previewed audit ledger archive cleanup without moving files.",
            "audit_ledger_cleanup_rolled_back" => "Restored audit ledger archive files from a cleanup summary.",
            "audit_ledger_cleanup_summary" => "Summary of an audit ledger archive cleanup pass.",
            "ai_identity_set" => "Updated Wevito's local AI identity name.",
            "agent_slot_assigned" => "Assigned a visible pet to an agent slot.",
            "agent_slot_renamed" => "Updated an agent slot name from the active pet roster.",
            "agent_slot_status_changed" => "Updated an agent slot status.",
            "assetInventory" => "Reviewed the local asset inventory.",
            "audioAssist" => "Prepared an audio helper result.",
            "autonomous_scope_enabled_changed" => "User changed an autonomous loop scope toggle.",
            "autonomous_scope_preview" => "Previewed what an autonomous scope would do without changing files or settings.",
            "autonomous_scope_tick" => "Autonomous loop tick fired for a registered scope.",
            "benchmark_baseline_updated" => "Updated a benchmark baseline after a reviewed measurement run.",
            "benchmark_case_approved" => "Approved a reviewed benchmark case.",
            "benchmark_case_bookmarked_from_chat" => "Saved an assistant chat response as a draft benchmark case.",
            "benchmark_case_drafted" => "Drafted a benchmark case for review.",
            "benchmark_case_rejected" => "Rejected a draft benchmark case.",
            "benchmark_case_revised" => "Revised a draft benchmark case.",
            "benchmark_regression_detected" => "Detected a benchmark regression and selected the required safety response.",
            "benchmark_run" => "Ran the local benchmark suite and recorded the per-axis results.",
            "buildProof" => "Prepared or ran a build proof.",
            "chat_search_performed" => "Searched local chat history.",
            "chat_session_archived" => "Archived an inactive chat session to cold local storage.",
            "chat_session_started" => "Started a local chat session.",
            "chat_session_title_set" => "Named a local chat session.",
            "chat_turn_cancelled" => "Cancelled a local chat response safely.",
            "chat_turn_completed" => "Completed a local chat response.",
            "codePatchPlan" => "Prepared a code-fix plan.",
            "codeReview" => "Reviewed code and wrote a report.",
            "codex_loop_heartbeat" => "Recorded that the Codex phase loop is still alive.",
            "codex_loop_paused" => "Paused the Codex phase loop.",
            "codex_loop_resumed" => "Resumed the Codex phase loop.",
            "codex_compile_throttled" => "Limited Codex compile/test parallelism so the user's PC stays responsive.",
            "codex_phase_blocked" => "Blocked a Codex phase and recorded the reason.",
            "codex_phase_completed" => "Completed a Codex phase after validation.",
            "codex_phase_retried" => "Retried a Codex phase once with failure context.",
            "codex_phase_started" => "Started a Codex phase from the phase queue.",
            "coexistence_trigger_cleared" => "Cleared a PC-coexistence pause after the user workload was safe again.",
            "coexistence_trigger_fired" => "Paused helper work because a PC-coexistence trigger fired.",
            "context_budget_pressure" => "Detected that a chat session is approaching its context budget.",
            "dnd_state_changed" => "Updated Do Not Disturb state for helper work.",
            "disk_io_budget_throttled" => "Paused background disk writes briefly so active PC use stays smooth.",
            "evidence_dashboard_summary_exported" => "Exported the Evidence dashboard summary.",
            "audio_played" => "Played a user-triggered pet sound after checking the audio policy.",
            "focus_protected" => "Showed a Wevito window without stealing focus from the user's current app.",
            "game_mode_detected" => "Entered coexistence protection because Windows Game Mode is active.",
            "game_mode_cleared" => "Cleared the Windows Game Mode coexistence signal.",
            "guardedMutation" => "Prepared a guarded mutation preview.",
            "kill_switch" => "Blocked helper work because Stop Everything is active.",
            "learning_promotion" => "Promoted reviewed learning data.",
            "localDocs" => "Summarized local project documents.",
            "local_document_index_built" => "Built the local document search index.",
            "local_document_index_refused" => "Refused a local document index or query request for safety.",
            "local_document_query_completed" => "Searched the local document index.",
            "local_brain_heartbeat" => "Recorded a local brain heartbeat probe.",
            "local_brain_onboarding_panel_shown" => "Showed the local brain runtime onboarding panel.",
            "local_brain_setup_instruction_copied" => "Copied a local brain setup instruction.",
            "local_brain_smoke_test_completed" => "Completed the local brain benchmark smoke test.",
            "local_brain_status_panel_shown" => "Showed the local brain status panel.",
            "local_file_preview" => "Previewed approved local file access.",
            "local_model_call" => "Prepared a local model response.",
            "model_bootstrap_required" => "Local reasoning model needs to be pulled before chat can use it.",
            "model_bootstrap_runtime_absent" => "Local Ollama runtime was not reachable, so Wevito used safe fallback behavior.",
            "mutation_apply" => "Applied a reviewed guarded mutation.",
            "mutation_proposal" => "Prepared a mutation proposal.",
            "mutation_rollback" => "Rolled back a guarded mutation.",
            "multi_monitor_preference_set" => "Saved the preferred monitor for Wevito's pet windows.",
            "notification_deferred" => "Deferred a helper notification until the user is idle.",
            "notification_delivered" => "Delivered a helper notification without stealing focus.",
            "petState" => "Reviewed pet state.",
            "pet_animation_forced" => "Temporarily showed a calm pet animation while helper work yielded.",
            "pet_cursor_curiosity_fired" => "Recorded a nearby-cursor pet curiosity moment.",
            "pet_goal_changed" => "Recorded a pet choosing a local behavior goal.",
            "pet_interaction_logged" => "Recorded a user pet interaction for local context.",
            "pet_micro_behavior" => "Recorded aggregated pet idle micro-behavior.",
            "pet_particle_effect_played" => "Recorded aggregated pet visual particle effects.",
            "pet_state_tool_invoked" => "Read current pet state through the local read-only policy gate.",
            "pet_fps_snapshot" => "Recorded pet-game frame-rate health.",
            "pet_fps_violation" => "Protected the pet game after frame rate fell below the floor.",
            "pet_cursor_reactivity_fired" => "Let a pet react briefly to the nearby cursor without taking focus.",
            "pinned_message_added" => "Pinned a chat message into the local context budget.",
            "pinned_message_removed" => "Soft-unpinned a chat message from the local context budget.",
            "proof_packet" => "Recorded a proof packet.",
            "process_crash_recovery" => "Recorded child-process crash recovery status.",
            "process_priority_set" => "Set a Wevito process to background-friendly priority.",
            "process_priority_boosted" => "Temporarily boosted a Wevito process for a foreground user action.",
            "promotion_criteria_snapshot" => "Computed the autonomous-beta promotion criteria snapshot.",
            "promotion_decision" => "Recorded an autonomous-beta promotion decision packet.",
            "ram_pressure_event" => "Reduced AI work because system memory was low.",
            "ram_pressure_emergency" => "Stopped helper work because memory pressure was unsafe.",
            "budget_meter_snapshot" => "Recorded the daily resource budget snapshot.",
            "focus_steal_snapshot" => "Recorded the daily focus-steal counter snapshot.",
            "first_launch_completed" => "Completed the first-launch setup wizard.",
            "first_launch_step_completed" => "Completed one step of the first-launch setup wizard.",
            "first_run_choice_recorded" => "Recorded the user's first-run intent choice.",
            "image_gen_idle_guard_blocked" => "Blocked background image generation because a pet was not idle.",
            "power_sleep" => "Wevito entered Quiet mode because the system slept.",
            "power_resume" => "Wevito recorded the system resuming.",
            "runtime_session" => "Recorded runtime supervisor activity.",
            "runtime_session_start" => "Wevito recorded the start of an active runtime session.",
            "runtime_session_heartbeat" => "Wevito recorded a runtime session heartbeat (still alive).",
            "runtime_session_end" => "Wevito recorded the end of an active runtime session.",
            "runtime_session_paused" => "Wevito paused background work because Stop Everything is active.",
            "runtime_autonomous_beta_user_consent" => "Recorded explicit user consent to enable the autonomous-beta loop.",
            "retrieval_triggered" => "Retrieved relevant local memory for a chat turn.",
            "scheduler_proposal" => "Proposed a background helper task.",
            "screenCapture" => "Prepared a screen capture helper result.",
            "session_lock" => "Wevito entered Quiet mode because the session locked.",
            "session_unlock" => "Wevito recorded the session unlocking.",
            SelfImprovementPacketKinds.ProposalDrafted => "Wevito drafted a supervised self-improvement proposal for review.",
            SelfImprovementPacketKinds.ConstitutionalReviewed => "Wevito checked a self-improvement proposal against its safety rules.",
            SelfImprovementPacketKinds.DryRunCompleted => "Wevito completed a self-improvement dry run without applying changes.",
            SelfImprovementPacketKinds.EvalCompleted => "Wevito completed the required self-improvement evaluation gates.",
            SelfImprovementPacketKinds.ApplyAwaitingApproval => "A self-improvement apply step is waiting for explicit user approval.",
            SelfImprovementPacketKinds.ApplyRefused => "Wevito refused a self-improvement apply step for safety.",
            SelfImprovementPacketKinds.ApplyCompleted => "Wevito applied an explicitly approved self-improvement change.",
            SelfImprovementPacketKinds.RollbackVerified => "Wevito verified the rollback path for a self-improvement change.",
            SelfImprovementPacketKinds.MaturityClockReset => "Wevito reset a self-improvement maturity clock after a safety condition changed.",
            SelfImprovementPacketKinds.JudgeCritique => "Wevito ran a deterministic critique over a self-improvement proposal.",
            SelfImprovementPacketKinds.ApplyPrerequisiteCheck => "Self-improvement apply runner prerequisite checklist; lists every gate that must pass before any future apply runner is permitted to run.",
            SelfImprovementPacketKinds.LocalRuntimeProbe => "Self-improvement local runtime check: probed whether the local Ollama runtime is reachable on loopback and whether the configured model is present. No prompt was sent.",
            SelfImprovementPacketKinds.ScoringDryRun => "Dry-run of the supervised self-improvement scoring contract. Carries no raw prompt and never mutates code.",
            SelfImprovementPacketKinds.ApplyRunnerStatusReport => "Recorded that the supervised self-improvement apply runner is still not implemented and listed every condition that would have to flip before it could be.",
            "soak_window_end" => "Recorded the end of an evidence-collection soak window.",
            "spriteAudit" => "Audited sprite or animation files.",
            "sprite_cleanup_help_card_drafted" => "Drafted a sprite-cleanup help task card from first-run choice.",
            "sprite_repair_queue_built" => "Built the sprite repair queue from visual QA evidence.",
            "sprite_repair_batch" => "Applied a single-family sprite repair batch with backup and post-proof.",
            "sprite_repair_batch_rolled_back" => "Rolled back a sprite repair batch after post-proof failed.",
            "sprite_repair_triage_card_enriched" => "Sprite repair triage drafted a task card with review-only plan details.",
            "sprite_repair_triage_card_drafted" => "Sprite repair triage drafted a task card for user review.",
            "summarization_run" => "Summarized older chat turns into local memory.",
            "train_plan" => "Prepared a local training plan.",
            "translateText" => "Prepared a translation result.",
            "tuning_apply" => "Applied reviewed local tuning configuration.",
            "tuning_rollback" => "Rolled back local tuning configuration.",
            "tool_invocation_started" => "Started an AI-requested local tool invocation.",
            "tool_invocation_completed" => "Completed an AI-requested local tool invocation.",
            "tool_hub_layout_changed" => "Loaded the simplified Tool Hub layout catalog.",
            "tool_result_truncated" => "Shortened a large tool result and saved the full result to disk.",
            "tool_registry_loaded" => "Loaded the AI-callable local tool registry.",
            "tool_registry_setting" => "Changed a local tool registry setting.",
            "tier_priority_adjusted" => "Adjusted helper work priority so foreground PC use stays protected.",
            "user_interacting_state_entered" => "Paused background AI because the user interacted with a pet.",
            "user_interacting_state_cleared" => "Cleared the short pet-interaction pause.",
            "user_protection_floor_blocked_reservation" => "Blocked background helper work to preserve CPU, GPU, or RAM for the user.",
            "web_fetch" => "Fetched approved web research records.",
            _ => WarnUnknown(packetKind)
        };
    }

    private string WarnUnknown(string packetKind)
    {
        _warnUnknownPacketKind?.Invoke(packetKind);
        return $"Unknown {packetKind}";
    }
}
